Functionally Running

diff --git a/init-rem_server b/init-rem_server
--- a/init-rem_server
+++ b/init-rem_server
@@ -8,40 +8,44 @@
 # directory in the user's $HOME directory, and remotely execute the newly
 # installed 'init-server' script to configure the server as a Laravel/LAMP
 # server.
+#
 
-#TODO Check that required packages are insalled locally
-#TODO Check that required files exist in the current directory
-#TODO Move verbose param print to its own function. Impliment cli flags
 
 ## Connection parameters
 uid='ubuntu'
-remoteHost="$1"
 scriptDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 resourceDir="$scriptDir/resource"
 destDir="/home/$uid"
-
+remoteHost="$1"
 
 clear
 printf "=======================================================================\n"
 printf "                        Initializing Remote Server\n"
 printf "=======================================================================\n"
-printf "      Remote Host:        %s\n" "$remoteHost"
-printf "      Remote UID:         %s\n" "$uid"
-printf "\n"
-printf "      Local Resource Dir: %s\n" "$resourceDir"
-printf "      Remote Dest Dir:    %s\n" "$destDir"
-printf "\n"
-printf "      Script Dir:         %s\n" "$scriptDir"
-printf "=======================================================================\n"
+# printf "      Remote Host:        %s\n" "$remoteHost"
+# printf "      Remote UID:         %s\n" "$uid"
+# printf "\n"
+# printf "      Local Resource Dir: %s\n" "$resourceDir"
+# printf "      Remote Dest Dir:    %s\n" "$destDir"
+# printf "\n"
+# printf "      Script Dir:         %s\n" "$scriptDir"
+# printf "=======================================================================\n"
+
+if [[ -z $1 ]]; then
+  printf "    - ERROR: No host alias provided. Exiting.\n\n\n"
+  exit 100;
+else
+  remoteHost="$1"
+fi
 
 
   # Create remote 'scripts' directory
 if
   ssh "$remoteHost" mkdir /home/"$uid"/scripts 2> /dev/null;
 then
-   printf "   - Created 'scripts' directory on remote\n"
+  printf "    - Created 'scripts' directory on remote\n"
 else
-  printf "    - WARNING: Could not create remote directory\n";
+  printf "    - WARNING: Could not create remote directory, continuing.\n";
 fi
 
   # Copy files to remote host using scp
@@ -52,5 +56,11 @@ then
   printf "[Success]\n"
 else
   printf "[FAILURE]\n"
+  exit 105;
 fi
-printf "===== [DONE] =====\n\n"
+
+printf "    - Initialize remote server environment: "
+ssh "$remoteHost" "$destDir/scripts/init-environment";
+
+
+printf "\n"
diff --git a/resource/init-environment b/resource/init-environment
--- a/resource/init-environment
+++ b/resource/init-environment
@@ -13,48 +13,105 @@
 declare -x TERM='xterm'
 scriptDir=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
 
-clear
 printf "\n"
-printf "======================================================================\n"
-printf "            Initializing/Upgrading Server Environment\n"
-printf "======================================================================\n"
-printf "      Script Dir:         %s\n" "$scriptDir"
-printf "=======================================================================\n"
+# printf "======================================================================\n"
+# printf "            Initializing/Upgrading Server Environment\n"
+# printf "======================================================================\n"
+# printf "      Script Dir:         %s\n" "$scriptDir"
+# printf "======================================================================\n"
+
+if
+  cd "$scriptDir";
+then
+  printf "    - Switched to Scripts directory\n"
+else
+  printf "    - FOXTROT!\n" && exit 150;
+fi
 
 if
   ! [ -f "$scriptDir"/bash_aliases ];
 then
-  printf "    - bash_aliases File does not exist\n"
+  printf "    - bash_aliases File does not exist [Skipping]\n"
 else
-  printf "    - Installing 'bash_aliases' file\n"
+  printf "    - Installing 'bash_aliases' file: "
   cp bash_aliases ~/.bash_aliases
+  printf " [Success]\n"
 fi
-
 
 if
   ! [ -f "$scriptDir"/profile ];
 then
-  printf "    - profile File does not exist\n"
+  printf "    - profile File does not exist [Skipping]\n"
 else
-  printf "    - Installing 'profile' file\n"
+  printf "    - Installing 'profile' file: "
   mv "$HOME/.profile" "$HOME/.profile.bak"
   mv profile ~/.profile
   source "$HOME/.profile"
-
-  # cp profile "$HOME/.profile"|| printf "ERROR: Could not create '.bash_aliases'\n" && exit 115
-
-
-
-
-
+  printf " [Success]\n"
 fi
 
-printf "    - Updating system indexes\n"
-sudo apt update -y  > /dev/null 2>&1
-printf "    - Upgrading packages (Takes a few minutes)\n"
-sudo apt upgrade -y > /dev/null 2>&1
-printf "===== [DONE] =====\n\n"
-#  inst_lamp
-#  wwwperms
-# inst_composer
-# inst_laravel
+printf "    - Updating system indexes: "
+if
+  sudo apt update -y  > /dev/null 2>&1;
+then
+  printf " [Success]\n"
+else
+  printf " [Failure]\n"
+  exit 155;
+fi
+
+
+
+printf "    - Upgrading packages (Takes a few minutes): "
+if
+  sudo apt upgrade -y > /dev/null 2>&1;
+then
+  printf " [Success]\n"
+else
+  printf " [Failure]\n";
+  exit 160;
+fi
+
+printf "    - Updating OS to Ubuntu 23.10 (About 7 minutes ): "
+if
+  sudo ./upgrade-dist  > /dev/null 2>&1
+then
+  printf " [Success]\n"
+else
+  printf " [Failure]\n"
+  exit 165;
+fi
+
+printf "    - Installing LAMP stack: "
+if
+  sudo ./inst-lamp
+  # sudo ./inst-lamp  > /dev/null 2>&1
+then
+  printf " [Success]\n"
+else
+  printf " [Failure]\n"
+  exit 170;
+fi
+./wwwperms  > /dev/null 2>&1
+
+printf "    - Installing Composer: "
+if
+  # sudo ./inst-composer  > /dev/null 2>&1
+  sudo ./inst-composer
+then
+  printf " [Success]\n"
+else
+  printf " [Failure]\n"
+  exit 175;
+fi
+./wwwperms  > /dev/null 2>&1
+
+printf "    - Installing Laravel: "
+if
+  ./inst-laravel > /dev/null 2>&1
+then
+  printf " [Success]\n"
+else
+  printf " [Failure]\n"
+  exit 180;
+fi
